name: Create Release - APXIV

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
        type: string

permissions:
  actions: read
  contents: write

jobs:
  create-release:
    name: Release FFXIV apworld
    runs-on: ubuntu-latest

    steps:
      - name: Set expected file basename to env
        run: echo "BASENAME=ffxiv" >> "$GITHUB_ENV"
      - name: Format changelog input as multiline string and put into env
        run: |
          echo 'CHANGELOG<<EOF' >> "$GITHUB_ENV"
          echo "${{ github.event.inputs.changelog }}" >> "$GITHUB_ENV"
          echo 'EOF' >> "$GITHUB_ENV"
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Create apworld file
        # rename src folder, zip it, change extension
        run: |
          mv src ${{ env.BASENAME }}
          zip -r ${{ env.BASENAME }}.zip ${{ env.BASENAME }}/*
          mv ${{ env.BASENAME }}.zip ${{ env.BASENAME }}.apworld
      - name: Upload apworld as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.BASENAME }}.apworld
          path: ${{ env.BASENAME }}.apworld
          if-no-files-found: error
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          name: ${{ github.event.inputs.version }}
          tag: ${{ env.event.inputs.version }}
          commit: ${{ env.GITHUB_REF }}
          artifacts: "${{ env.BASENAME }}.apworld"
